version: '3.8'

services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "6006:6006"
    environment:
      - NODE_ENV=development
      - CI=true
    restart: always 